-- Enable Row Level Security (RLS)
-- Create Profiles Table (Public User Info)
create table profiles (
  id uuid references auth.users not null,
  email text,
  role text default 'Manager',
  avatar_url text,
  updated_at timestamp with time zone,
  primary key (id),
  constraint username_length check (char_length(role) >= 3)
);

alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text,
  sku text,
  price numeric,
  stock integer,
  sales integer,
  revenue numeric,
  platform text,
  status text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table products enable row level security;

create policy "Users can view their own products"
  on products for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own products"
  on products for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own products"
  on products for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own products"
  on products for delete
  using ( auth.uid() = user_id );

-- Create Settings Table (User Preferences)
create table settings (
  user_id uuid references auth.users not null primary key,
  currency text default '฿',
  theme text default 'default',
  notifications jsonb default '{}'::jsonb,
  updated_at timestamp with time zone
);

alter table settings enable row level security;

create policy "Users can view own settings"
  on settings for select
  using ( auth.uid() = user_id );

create policy "Users can update own settings"
  on settings for update
  using ( auth.uid() = user_id );

create policy "Users can insert own settings"
  on settings for insert
  with check ( auth.uid() = user_id );
